# -*- coding: utf-8 -*-
"""Native Odoo commercial documents generated from a completed freight file."""

from odoo import api, fields, models, _
from odoo.exceptions import UserError, ValidationError


class DallyShipment(models.Model):
    _inherit = "dally.shipment"

    dossier_fee_eur = fields.Monetary(
        string="Dossier Fee",
        currency_field="billing_currency_id",
        default=0.0,
    )
    other_fees_eur = fields.Monetary(
        string="Other Fees",
        currency_field="billing_currency_id",
        default=0.0,
    )
    billing_currency_id = fields.Many2one(
        "res.currency",
        string="Billing Currency",
        required=True,
        default=lambda self: self.env.ref("base.EUR"),
    )
    freight_amount_eur = fields.Monetary(
        string="Freight Amount",
        currency_field="billing_currency_id",
        compute="_compute_billing_totals",
        store=True,
    )
    billing_total_eur = fields.Monetary(
        string="Billing Total",
        currency_field="billing_currency_id",
        compute="_compute_billing_totals",
        store=True,
    )
    billing_locked = fields.Boolean(
        string="Billing Locked",
        default=False,
        copy=False,
        help=(
            "Set when the native sales order and draft invoice are generated. "
            "Sheet cargo changes are then refused until Finance explicitly "
            "resets the draft documents."
        ),
    )

    @api.depends(
        "package_ids.transport_amount_eur",
        "dossier_fee_eur",
        "other_fees_eur",
    )
    def _compute_billing_totals(self):
        for shipment in self:
            shipment.freight_amount_eur = sum(
                shipment.package_ids.mapped("transport_amount_eur")
            )
            shipment.billing_total_eur = (
                shipment.freight_amount_eur
                + (shipment.dossier_fee_eur or 0.0)
                + (shipment.other_fees_eur or 0.0)
            )

    @api.constrains("dossier_fee_eur", "other_fees_eur")
    def _check_non_negative_fees(self):
        for shipment in self:
            if shipment.dossier_fee_eur < 0 or shipment.other_fees_eur < 0:
                raise ValidationError(_("Freight fees cannot be negative."))

    def _check_ready_for_native_invoice(self):
        self.ensure_one()
        if not self.partner_id:
            raise UserError(_("A customer is required before invoicing."))
        if not self.package_ids:
            raise UserError(_("At least one freight article is required before invoicing."))
        if self.invoice_id:
            raise UserError(
                _("This freight file is already linked to invoice %s.", self.invoice_id.display_name)
            )
        if self.sale_order_id and self.sale_order_id.dally_freight_shipment_id != self:
            raise UserError(
                _(
                    "This shipment is already linked to sales order %(order)s, "
                    "which was not generated by the Freight billing engine. "
                    "Use that sales order's native invoicing workflow."
                )
                % {"order": self.sale_order_id.display_name}
            )

        incomplete = self.package_ids.filtered(
            lambda line: (
                line.billing_method == "quote"
                or not line.tariff_applied_on
                or line.billable_weight_kg <= 0
            )
        )
        if incomplete:
            keys = ", ".join(
                incomplete.mapped("external_line_key") or incomplete.mapped("description")
            )
            raise UserError(
                _("Some freight lines are not ready for invoicing: %s", keys or "-")
            )
        return True

    def action_prepare_native_freight_invoice(self):
        """Create one confirmed native SO then one *draft* customer invoice.

        Confirmation is required by Odoo's standard ``_create_invoices`` flow.
        Products are services, therefore this confirmation creates no stock
        picking.  The invoice itself is deliberately left in ``draft``: posting
        remains a Finance decision.
        """
        self.ensure_one()
        self._check_ready_for_native_invoice()

        # Serialize callers from a button, API retry or concurrent Apps Script
        # execution.  The record is re-read after the lock before creating docs.
        self.env.cr.execute(
            'SELECT id FROM dally_shipment WHERE id = %s FOR UPDATE',
            [self.id],
        )
        self.invalidate_recordset(["sale_order_id", "invoice_id", "billing_locked"])
        if self.invoice_id:
            return self.invoice_id

        order = self.sale_order_id
        if not order:
            order = self._create_native_freight_sale_order()
            self.sale_order_id = order.id

        if order.state in ("draft", "sent"):
            order.action_confirm()
        if order.state != "sale":
            raise UserError(
                _("Freight sales order %s is not in a confirmable state.", order.display_name)
            )

        invoices = order._create_invoices()
        invoice = invoices.filtered(lambda move: move.move_type == "out_invoice")[:1]
        if not invoice:
            raise UserError(_("Odoo did not create a customer invoice for this freight order."))
        if invoice.state != "draft":
            raise UserError(
                _("The generated freight invoice must remain a draft until Finance validates it.")
            )

        invoice.dally_freight_shipment_id = self.id
        self.write({
            "invoice_id": invoice.id,
            "billing_locked": True,
        })
        return invoice

    def _create_native_freight_sale_order(self):
        self.ensure_one()
        pricelist = self.env.ref("dally_freight_billing.pricelist_freight_eur")
        transport_product = self.env.ref(
            "dally_freight_billing.product_freight_transport_template"
        ).product_variant_id
        fee_product = self.env.ref(
            "dally_freight_billing.product_freight_fee_template"
        ).product_variant_id

        order = self.env["sale.order"].create({
            "partner_id": self.partner_id.id,
            "company_id": self.company_id.id,
            "pricelist_id": pricelist.id,
            "origin": self.external_reference or self.reference,
            "client_order_ref": self.external_reference or False,
            "dally_freight_shipment_id": self.id,
        })

        mode_label = dict(self._fields["transport_mode"].selection).get(
            self.transport_mode,
            self.transport_mode,
        )
        sequence = 10
        for package in self.package_ids.sorted(key=lambda line: (line.sequence, line.id)):
            description = package.description or self.goods_description or _("Freight")
            self.env["sale.order.line"].create({
                "order_id": order.id,
                "sequence": sequence,
                "product_id": transport_product.id,
                "product_uom_id": self.env.ref("uom.product_uom_kgm").id,
                "product_uom_qty": package.billable_weight_kg,
                "price_unit": package.applied_unit_price_eur,
                "name": _("%(mode)s — %(description)s", mode=mode_label, description=description),
                "dally_freight_package_id": package.id,
            })
            sequence += 10

        for label, amount in (
            (_("Frais de dossier"), self.dossier_fee_eur),
            (_("Autres frais"), self.other_fees_eur),
        ):
            if amount:
                self.env["sale.order.line"].create({
                    "order_id": order.id,
                    "sequence": sequence,
                    "product_id": fee_product.id,
                    "product_uom_id": self.env.ref("uom.product_uom_unit").id,
                    "product_uom_qty": 1.0,
                    "price_unit": amount,
                    "name": label,
                })
                sequence += 10

        return order

    def action_reset_draft_freight_billing(self):
        """Remove generated draft documents so corrected Sheet data can sync.

        Only documents still fully reversible are accepted.  A posted invoice is
        accounting history and is never deleted or rewritten by this module.
        """
        for shipment in self:
            invoice = shipment.invoice_id
            order = shipment.sale_order_id

            if invoice and invoice.state not in ("draft", "cancel"):
                raise UserError(
                    _("Posted invoice %s cannot be reset by Freight sync.", invoice.display_name)
                )
            if invoice and invoice.state == "draft":
                invoice.unlink()
            elif invoice and invoice.state == "cancel":
                invoice.unlink()

            if order:
                if order.state == "sale":
                    order.action_cancel()
                if order.state != "cancel":
                    raise UserError(
                        _("Sales order %s cannot be safely reset.", order.display_name)
                    )
                order.unlink()

            shipment.write({
                "invoice_id": False,
                "sale_order_id": False,
                "billing_locked": False,
            })
        return True


class SaleOrder(models.Model):
    _inherit = "sale.order"

    dally_freight_shipment_id = fields.Many2one(
        "dally.shipment",
        string="Freight Shipment",
        index=True,
        copy=False,
        ondelete="restrict",
    )

    _dally_freight_shipment_order_unique = models.Constraint(
        "UNIQUE(dally_freight_shipment_id)",
        "A freight shipment can generate only one native sales order.",
    )


class SaleOrderLine(models.Model):
    _inherit = "sale.order.line"

    dally_freight_package_id = fields.Many2one(
        "dally.shipment.package",
        string="Freight Article",
        index=True,
        copy=False,
        ondelete="restrict",
    )

    _dally_freight_package_sale_line_unique = models.Constraint(
        "UNIQUE(dally_freight_package_id)",
        "A freight article can appear only once in the generated sales lines.",
    )


class AccountMove(models.Model):
    _inherit = "account.move"

    dally_freight_shipment_id = fields.Many2one(
        "dally.shipment",
        string="Freight Shipment",
        index=True,
        copy=False,
        ondelete="restrict",
    )

    _dally_freight_shipment_invoice_unique = models.Constraint(
        "UNIQUE(dally_freight_shipment_id)",
        "A freight shipment can be linked to only one generated invoice.",
    )
