# -*- coding: utf-8 -*-
"""Tracking events — the narrative of a shipment.

Every event carries one bit that decides everything: ``visible_to_customer``.
An internal event ("agent has not confirmed the booking, chase tomorrow") and a
customer event ("goods loaded in Le Havre") live in the same table and are
distinguished only by that flag, so the flag defaults to **False**.

That default is deliberate. Defaulting to visible would mean a single forgotten
checkbox publishes an internal note, and the mistake would only be discovered by
the customer reading it.
"""

from odoo import _, api, fields, models
from odoo.exceptions import ValidationError

from odoo.addons.dally_freight.models.dally_shipment import SHIPMENT_STATES


class DallyShipmentEvent(models.Model):
    _name = "dally.shipment.event"
    _description = "DallyTrading Shipment Event"
    # Newest first in the interface; the public timeline is re-sorted
    # chronologically, which is how a customer reads a journey.
    _order = "event_date desc, id desc"
    _rec_name = "description"

    shipment_id = fields.Many2one(
        comodel_name="dally.shipment",
        string="Shipment",
        required=True,
        ondelete="cascade",
        index=True,
    )
    company_id = fields.Many2one(
        related="shipment_id.company_id",
        store=True,
        index=True,
        readonly=True,
    )

    event_date = fields.Datetime(
        string="Date",
        required=True,
        default=fields.Datetime.now,
        index=True,
    )
    status = fields.Selection(
        selection=SHIPMENT_STATES,
        string="Status",
        required=True,
        help="Shipment status this event reports. Reuses the shipment's own "
             "status list so the timeline and the file can never tell different "
             "stories.",
    )
    location = fields.Char(
        string="Location",
        help="Where it happened: port, airport, city or warehouse. "
             "Shown to the customer when the event is visible.",
    )
    description = fields.Char(
        string="Description",
        required=True,
        help="Customer-facing wording. Write it as the customer should read it: "
             "it is published verbatim when the event is visible.",
    )

    internal_note = fields.Text(
        string="Internal Note",
        help="Never published, whatever the value of 'Visible to Customer'. "
             "Use it freely for agent instructions and commercial context.",
    )

    visible_to_customer = fields.Boolean(
        string="Visible to Customer",
        default=False,
        index=True,
        help="Off by default, on purpose: a forgotten checkbox must fail closed, "
             "not publish an internal event.",
    )

    user_id = fields.Many2one(
        comodel_name="res.users",
        string="Recorded By",
        default=lambda self: self.env.user,
        readonly=True,
    )
    is_automatic = fields.Boolean(
        string="Automatic",
        default=False,
        readonly=True,
        help="Generated by a status change rather than entered by hand.",
    )

    attachment_ids = fields.Many2many(
        comodel_name="ir.attachment",
        string="Documents",
        help="Bill of lading, photos, delivery note. Attachments are NEVER "
             "returned by the public tracking API, even on a visible event: "
             "publishing a document is a separate decision from publishing an "
             "event, and the API has no way to make it.",
    )

    _dally_event_description_not_empty = models.Constraint(
        "CHECK(description <> '')",
        'An event must have a description.',
    )

    @api.constrains("visible_to_customer", "description")
    def _check_public_description(self):
        """A published event needs a description a customer can understand.

        Three characters is not a status update; it is a placeholder somebody
        meant to come back to.
        """
        for event in self:
            if event.visible_to_customer and len(
                (event.description or "").strip()
            ) < 4:
                raise ValidationError(
                    _(
                        "A customer-visible event needs a meaningful description. "
                        "It is published exactly as written."
                    )
                )

    def name_get(self):
        result = []
        for event in self:
            label = event.description or ""
            if event.location:
                label = "%s — %s" % (label, event.location)
            result.append((event.id, label))
        return result

    # ─── Public projection ───────────────────────────────────────────

    def _dally_public_event_payload(self):
        """Return the customer-facing view of these events.

        Built by naming each key explicitly rather than by removing unwanted ones.
        An allowlist stays correct when a field is added later; a denylist quietly
        starts leaking.

        Note what is absent: ``internal_note``, ``user_id``, ``attachment_ids``,
        ``id``, ``is_automatic``.
        """
        translated_states = dict(
            self._fields["status"]._description_selection(self.env)
        )

        payload = []
        for event in self.sorted(key=lambda e: (e.event_date, e.id)):
            if not event.visible_to_customer:
                # Defence in depth: callers are expected to filter, and this
                # refuses to publish anyway.
                continue
            payload.append({
                "date": event.event_date.isoformat() if event.event_date else None,
                "status": event.status,
                "statusLabel": translated_states.get(event.status, event.status),
                "location": event.location or None,
                "description": event.description or None,
            })
        return payload
