#!/usr/bin/env python3
from pathlib import Path

path = Path("integrations/google-sheets/freight-sync/Code.gs")
text = path.read_text(encoding="utf-8")

old = """function buildLine_(row) {\n  const family = display_(row, DALLY.columns.tariffFamily);\n  const pricingType = display_(row, DALLY.columns.pricingType);\n  const out = {\n    external_line_key: articleKey_(row),\n    package_type: 'parcel',\n    description: display_(row, DALLY.columns.description),\n    goods_category: display_(row, DALLY.columns.goodsCategory),\n    quantity: numberOr_(value_(row, DALLY.columns.quantity), 1),\n    announced_weight_kg: numberOrNull_(value_(row, DALLY.columns.announcedWeight)),\n    exact_weight_kg: numberOrNull_(value_(row, DALLY.columns.exactWeight)),\n    length_cm: numberOrNull_(value_(row, DALLY.columns.length)),\n    width_cm: numberOrNull_(value_(row, DALLY.columns.width)),\n    height_cm: numberOrNull_(value_(row, DALLY.columns.height)),\n    unit_volume_cbm: numberOrNull_(value_(row, DALLY.columns.unitVolume)),\n    total_volume_cbm: numberOrNull_(value_(row, DALLY.columns.totalVolume)),\n    billing_method: DALLY.billingCodes[display_(row, DALLY.columns.billingMethod)] || 'real',\n    tariff_family_code: DALLY.familyCodes[family],\n    manual_unit_price_eur: numberOrNull_(value_(row, DALLY.columns.manualPrice)),\n    pricing_type: DALLY.pricingCodes[pricingType] || 'standard',\n    pricing_reason: display_(row, DALLY.columns.pricingReason),\n    customs_value_xof: numberOrNull_(value_(row, DALLY.columns.customsValue)),\n  };\n  Object.keys(out).forEach(k => { if (out[k] === null || out[k] === '' || typeof out[k] === 'undefined') delete out[k]; });\n  return out;\n}\n"""

new = """function normalizeTariffFamilyLabel_(value) {\n  return String(value || '')\n    .replace(/[\\u00A0\\u202F]/g, ' ')\n    .normalize('NFD')\n    .replace(/[\\u0300-\\u036f]/g, '')\n    .replace(/\\s*\\/\\s*/g, ' / ')\n    .replace(/\\s+/g, ' ')\n    .trim()\n    .toLowerCase();\n}\n\nfunction tariffFamilyCode_(value) {\n  const raw = String(value || '').replace(/[\\u00A0\\u202F]/g, ' ').replace(/\\s+/g, ' ').trim();\n  if (!raw) return '';\n\n  const direct = DALLY.familyCodes[raw];\n  if (direct) return direct;\n\n  if (['food', 'seafood', 'honey', 'clothing', 'non_food'].includes(raw.toLowerCase())) {\n    return raw.toLowerCase();\n  }\n\n  const aliases = {\n    'alimentaire standard': 'food',\n    'halieutiques': 'seafood',\n    'miel': 'honey',\n    'habits / vetements': 'clothing',\n    'non alimentaire': 'non_food',\n  };\n  const code = aliases[normalizeTariffFamilyLabel_(raw)];\n  if (!code) throw new Error('Famille tarifaire non mappée: ' + raw);\n  return code;\n}\n\nfunction buildLine_(row) {\n  const family = display_(row, DALLY.columns.tariffFamily);\n  const familyCode = tariffFamilyCode_(family);\n  const pricingType = display_(row, DALLY.columns.pricingType);\n  const billingMethod = DALLY.billingCodes[display_(row, DALLY.columns.billingMethod)] || 'real';\n  const manualPrice = numberOrNull_(value_(row, DALLY.columns.manualPrice));\n  if (!familyCode && !manualPrice && billingMethod !== 'quote') {\n    throw new Error('Famille tarifaire obligatoire pour la tarification automatique: ' + display_(row, DALLY.columns.description));\n  }\n  const out = {\n    external_line_key: articleKey_(row),\n    package_type: 'parcel',\n    description: display_(row, DALLY.columns.description),\n    goods_category: display_(row, DALLY.columns.goodsCategory),\n    quantity: numberOr_(value_(row, DALLY.columns.quantity), 1),\n    announced_weight_kg: numberOrNull_(value_(row, DALLY.columns.announcedWeight)),\n    exact_weight_kg: numberOrNull_(value_(row, DALLY.columns.exactWeight)),\n    length_cm: numberOrNull_(value_(row, DALLY.columns.length)),\n    width_cm: numberOrNull_(value_(row, DALLY.columns.width)),\n    height_cm: numberOrNull_(value_(row, DALLY.columns.height)),\n    unit_volume_cbm: numberOrNull_(value_(row, DALLY.columns.unitVolume)),\n    total_volume_cbm: numberOrNull_(value_(row, DALLY.columns.totalVolume)),\n    billing_method: billingMethod,\n    tariff_family_code: familyCode || undefined,\n    manual_unit_price_eur: manualPrice,\n    pricing_type: DALLY.pricingCodes[pricingType] || 'standard',\n    pricing_reason: display_(row, DALLY.columns.pricingReason),\n    customs_value_xof: numberOrNull_(value_(row, DALLY.columns.customsValue)),\n  };\n  Object.keys(out).forEach(k => { if (out[k] === null || out[k] === '' || typeof out[k] === 'undefined') delete out[k]; });\n  return out;\n}\n"""

if new in text:
    print("PATCH_ALREADY_APPLIED")
    raise SystemExit(0)
if old not in text:
    raise SystemExit("Expected buildLine_ block not found; refusing to patch")

path.write_text(text.replace(old, new, 1), encoding="utf-8")
print("PATCH_APPLIED")
