/**
 * Validation of the public quote form.
 *
 * This schema is the authority, and it runs **server-side**. The browser uses the
 * same file for immediate feedback, but client validation is a convenience, never
 * a control: the API route is reachable with curl (§54).
 *
 * It deliberately does not mirror `LeadInput` field-for-field — it describes what
 * a *form submission* looks like, including the idempotency key the browser
 * generates. Mapping to the gateway type happens once, in `toLeadInput`.
 */

import { z } from 'zod';
import type { LeadInput } from '@/services/odoo/types';

/**
 * UUID matcher.
 *
 * A regex rather than a zod format helper: those moved from `z.string().uuid()`
 * to `z.uuid()` between major versions, and this check is too central to depend
 * on which spelling survives. Any version and variant is accepted —
 * `crypto.randomUUID()` produces v4.
 */
const UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/** Trim, then treat an empty string as absent. */
const optionalText = (max: number) =>
  z
    .string()
    .trim()
    .max(max)
    .transform((value) => (value === '' ? undefined : value))
    .optional();

/**
 * Structural email check.
 *
 * Full RFC 5322 validation rejects addresses that work in practice; deliverability
 * is proven by the confirmation e-mail actually arriving, not by a regex. This
 * catches typos and obvious junk, and nothing more.
 */
const email = z
  .string()
  .trim()
  .max(254)
  .refine((value) => {
    if (value === '') return true;
    const parts = value.split('@');
    if (parts.length !== 2) return false;
    const [local, domain] = parts;
    if (!local || !domain) return false;
    if (!domain.includes('.') || domain.startsWith('.') || domain.endsWith('.')) {
      return false;
    }
    return !/\s/.test(value);
  }, 'Adresse e-mail invalide')
  .transform((value) => (value === '' ? undefined : value))
  .optional();

/**
 * Phone number.
 *
 * Only length and character set are checked. Rejecting anything that is not a
 * canonical +221 number would turn away legitimate international prospects, which
 * for an import/export business is the wrong trade-off.
 */
const phone = z
  .string()
  .trim()
  .max(40)
  .refine((value) => {
    if (value === '') return true;
    const digits = value.replace(/\D/g, '');
    return digits.length >= 7 && digits.length <= 20;
  }, 'Numéro de téléphone invalide')
  .transform((value) => (value === '' ? undefined : value))
  .optional();

export const quoteFormSchema = z
  .object({
    /**
     * Generated by the browser, one per submission attempt. Sent unchanged on a
     * retry so that the retry is recognised as the same submission (§41).
     */
    requestUuid: z
      .string({ error: 'Identifiant de demande manquant' })
      .trim()
      .refine((value) => UUID_RE.test(value), 'Identifiant de demande invalide'),

    // The `error` option covers the missing/wrong-type case. Without it, an
    // absent field yields zod's English default ("expected string, received
    // undefined"), which would be shown verbatim to a French-speaking customer.
    serviceCode: z
      .string({ error: 'Veuillez sélectionner un service' })
      .trim()
      .min(1, 'Veuillez sélectionner un service')
      .max(50)
      // Mirrors the constraint enforced on dally.service.type codes.
      .regex(/^[a-z0-9_]+$/, 'Code de service invalide'),

    lastName: z
      .string({ error: 'Le nom est obligatoire' })
      .trim()
      .min(1, 'Le nom est obligatoire')
      .max(100),
    firstName: optionalText(100),
    companyName: optionalText(200),

    email,
    phone,
    whatsapp: phone,

    city: optionalText(100),
    countryCode: z
      .string()
      .trim()
      .length(2, 'Code pays invalide')
      .regex(/^[A-Za-z]{2}$/, 'Code pays invalide')
      .transform((value) => value.toUpperCase())
      .optional(),

    message: optionalText(20_000),

    // Attribution. Captured by the client, never trusted for anything but
    // reporting — a visitor can set these to whatever they like.
    sourceUrl: optionalText(500),
    utmSource: optionalText(100),
    utmMedium: optionalText(100),
    utmCampaign: optionalText(100),

    /**
     * Honeypot. Hidden from real users by CSS, so a filled value means an
     * automated submission. Cheap, invisible, and it never inconveniences a
     * genuine customer the way a CAPTCHA does (§54).
     */
    website: z.string().max(200).optional(),
  })
  // At least one way to reply. A request nobody can answer is not a lead.
  .refine((data) => Boolean(data.email ?? data.phone), {
    message: 'Indiquez au moins un e-mail ou un téléphone',
    path: ['email'],
  });

export type QuoteFormInput = z.input<typeof quoteFormSchema>;
export type QuoteFormData = z.output<typeof quoteFormSchema>;

/** True when the honeypot was filled, i.e. the submission is automated. */
export function isBotSubmission(data: QuoteFormData): boolean {
  return typeof data.website === 'string' && data.website.trim() !== '';
}

/**
 * Map validated form data onto the gateway input.
 *
 * The honeypot and the idempotency key are intentionally dropped: the first is
 * anti-spam plumbing, the second travels as a separate argument because it is a
 * property of the *call*, not of the lead.
 */
export function toLeadInput(data: QuoteFormData): LeadInput {
  return {
    serviceCode: data.serviceCode,
    lastName: data.lastName,
    ...(data.firstName !== undefined && { firstName: data.firstName }),
    ...(data.companyName !== undefined && { companyName: data.companyName }),
    ...(data.email !== undefined && { email: data.email }),
    ...(data.phone !== undefined && { phone: data.phone }),
    ...(data.whatsapp !== undefined && { whatsapp: data.whatsapp }),
    ...(data.city !== undefined && { city: data.city }),
    ...(data.countryCode !== undefined && { countryCode: data.countryCode }),
    ...(data.message !== undefined && { message: data.message }),
    ...(data.sourceUrl !== undefined && { sourceUrl: data.sourceUrl }),
    ...(data.utmSource !== undefined && { utmSource: data.utmSource }),
    ...(data.utmMedium !== undefined && { utmMedium: data.utmMedium }),
    ...(data.utmCampaign !== undefined && { utmCampaign: data.utmCampaign }),
  };
}
