# -*- coding: utf-8 -*-
{
    "name": "DallyTrading — Freight Billing Sync",
    "summary": "Tarification, facturation et synchronisation du cahier fret.",
    "version": "19.0.1.7.0",
    "license": "LGPL-3",
    "depends": [
        "dally_api",
        "dally_freight",
        "dally_tracking",
        "dally_crm",
        "sale",
        "account",
    ],
    "data": [
        "security/freight_sync_security.xml",
        "security/ir.model.access.csv",
        "data/freight_api_users.xml",
        "data/freight_tariff_data.xml",
        "data/freight_product_data.xml",
        "views/freight_tariff_views.xml",
        "views/shipment_billing_views.xml",
        "views/payment_collection_views.xml",
        "views/cash_operation_views.xml",
        "reports/freight_invoice_report.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
