from . import dally_shop_category
from . import shop_product_image
from . import product_template
from . import shop_order
from . import shop_delivery
from . import shop_delivery_currency
from . import shop_delivery_immutability
from . import shop_delivery_fields
from . import shop_delivery_atomic
from . import shop_order_workflow
from . import shop_fulfillment
from . import shop_confirmation_guard
from . import shop_shipping_management
from . import shop_order_workflow_projection
from . import shop_order_portal
from . import res_config_settings
